name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VM and run script
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GCLOUD_VM_IP }}  # Ваш IP-адрес Google Cloud VM
          username: ${{ secrets.GCLOUD_VM_USERNAME }}  # Ваше имя пользователя на VM
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Приватный ключ для доступа к VM
          script: |
            # Здесь выполните команды для клонирования репозитория и запуска вашего скрипта
            git clone git@github.com:BKS01/3wp-install.git
            cd ~
            sudo chmod 777 3wordpress_install.sh
            ./3wordpress_install.sh  
