name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VM and run script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCLOUD_VM_IP }}
          username: ${{ secrets.GCLOUD_VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            git clone git@github.com:BKS01/3wp-install.git
            cd 3wp-install/
            chmod +x 3wordpress_install.sh
            ./3wordpress_install.sh
